### ISSUE TITLE
Sudden crash 

### ISSUE THREAD

**Issue by kubrt-d** [gohornet/hornet#1281]
**Describe the bug**
Sudden crash 

```
Jan 22 20:14:44 robin hornet[3901434]: 2022-01-22T20:14:44Z#011INFO#011Tangle#011Valid milestone detected! Index: 2318855
Jan 22 20:14:44 robin hornet[3901434]: 2022-01-22T20:14:44Z#011INFO#011Tangle#011Run solidity check for Milestone (2318855)...
Jan 22 20:14:44 robin hornet[3901434]: 2022-01-22T20:14:44Z#011INFO#011Tangle#011Solidifier finished: msgs: 0, collect: 0s, solidity 0s, propagation: 0s, total: 0s
Jan 22 20:14:45 robin hornet[3901434]: 2022-01-22T20:14:45Z#011INFO#011Tangle#011Milestone confirmed (2318855): txsReferenced: 136, txsValue: 1, txsZeroValue: 135, txsConflicting: 0, collect: 52ms, total: 189ms
Jan 22 20:14:45 robin hornet[3901434]: 2022-01-22T20:14:45Z#011INFO#011Tangle#011New confirmed milestone: 2318855, 16.80 MPS, 13.60 RMPS, 80.95% ref.rate
Jan 22 20:14:45 robin hornet[3901434]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 2318855/2318855, MPS (in/new/out): 00063/00011/00058, Tips (non-/semi-lazy): 100/0
Jan 22 20:14:45 robin hornet[3901434]: 2022-01-22T20:14:45Z#011INFO#011P2P-Manager#011reconnecting <peer.ID 12*DuxR3Y>
Jan 22 20:14:45 robin hornet[3901434]: 2022-01-22T20:14:45Z#011INFO#011P2P-Manager#011scheduled reconnect in 30.696976443s to <peer.ID 12*DuxR3Y>
Jan 22 20:14:45 robin hornet[3901434]: 2022-01-22T20:14:45Z#011WARN#011P2P-Manager#011error reconnect <peer.ID 12*DuxR3Y>: failed to dial *****************************************************************************
Jan 22 20:14:45 robin hornet[3901434]:   * [/ip4/195.144.105.180/tcp/15600] dial backoff
Jan 22 20:14:46 robin hornet[3901434]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 2318855/2318855, MPS (in/new/out): 00103/00018/00095, Tips (non-/semi-lazy): 100/0
Jan 22 20:14:46 robin hornet[3901434]: panic: Corruption: bad entry in block
Jan 22 20:14:46 robin hornet[3901434]: goroutine 382 [running]:
Jan 22 20:14:46 robin hornet[3901434]: github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).LoadObjectFromStore(0xc00003e100, {0xc0044261e0, 0x20, 0x20})
Jan 22 20:14:46 robin hornet[3901434]: #011/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20211207105259-9e48241c18f7/objectstorage/object_storage.go:1002 +0x1c5
Jan 22 20:14:46 robin hornet[3901434]: github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).ComputeIfAbsent(0xc00003e100, {0xc0044261e0, 0x1305c0a, 0x5e6f01}, 0xc0044b6510)
Jan 22 20:14:46 robin hornet[3901434]: #011/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20211207105259-9e48241c18f7/objectstorage/object_storage.go:168 +0x125
Jan 22 20:14:46 robin hornet[3901434]: github.com/gohornet/hornet/pkg/model/storage.(*Storage).StoreMessageIfAbsent(0xc000e6c1a0, 0xc003dd4540)
Jan 22 20:14:46 robin hornet[3901434]: #011/__w/hornet/hornet/pkg/model/storage/messages_storage.go:278 +0x105
Jan 22 20:14:46 robin hornet[3901434]: github.com/gohornet/hornet/pkg/tangle.AddMessageToStorage(0x5c5b08, 0xc003603f70, 0x2, 0x1, 0x0, 0x0)
Jan 22 20:14:46 robin hornet[3901434]: #011/__w/hornet/hornet/pkg/tangle/message.go:15 +0x5a
Jan 22 20:14:46 robin hornet[3901434]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).processIncomingTx(0xc0001fc1c0, 0xc003dd4540, {0x0, 0x0, 0xc000e74360}, 0xc002430000)
Jan 22 20:14:46 robin hornet[3901434]: #011/__w/hornet/hornet/pkg/tangle/tangle_processor.go:198 +0xbd
Jan 22 20:14:46 robin hornet[3901434]: github.com/gohornet/hornet/pkg/tangle.(*Tangle).ConfigureTangleProcessor.func1({{0xc0044b64e0, 0x3, 0x3}, 0xc003dd45a0})
Jan 22 20:14:46 robin hornet[3901434]: #011/__w/hornet/hornet/pkg/tangle/tangle_processor.go:23 +0xae
Jan 22 20:14:46 robin hornet[3901434]: github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1()
Jan 22 20:14:46 robin hornet[3901434]: #011/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20211207105259-9e48241c18f7/workerpool/workerpool.go:164 +0x123
Jan 22 20:14:46 robin hornet[3901434]: created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
Jan 22 20:14:46 robin hornet[3901434]: #011/github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20211207105259-9e48241c18f7/workerpool/workerpool.go:140 +0x2c
```

**Environment information:**
 - OS: Debian Debian GNU/Linux 11 (bullseye)
 - RAM:  4 GB
 - Cores: 8
 - Type: VPS
 - HORNET version 1.1.3

**Comment by alexsporn** [comment]
Is your disk full? Can you please attach the `LOG` files inside the `mainnetdb/tangle` and `mainnetdb/utxo` directories?

**Comment by kubrt-d** [comment]
Hi Alex, no, the disk space is certainly not a problem. It's NAS though, so maybe some I/O glitch, although I have not experienced that with anything else. 
Unfortunately, the LOG files seem to be gone with `--deleteAll` I had to use to make the Hornet buzz again, I didn't have much time. I can restore it all from a daily backup though, but only if you think it's going to give you some valuable information. 
Thanks for a prompt response!
