### ISSUE TITLE
Investigate Hornet hangs during spam test

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1698]
After heavy spam, hornet doesn't receive any messages anymore, the tip pool is full, and it doesn't have requests at all.
Full stacktrace is available.

```
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 556/556, BPS (in/new/out): 00000/00000/00000, Tips (non-/semi-lazy): 10056/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 556/556, BPS (in/new/out): 00000/00000/00000, Tips (non-/semi-lazy): 10056/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 556/556, BPS (in/new/out): 00000/00000/00000, Tips (non-/semi-lazy): 10056/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 556/556, BPS (in/new/out): 00000/00000/00000, Tips (non-/semi-lazy): 10056/0
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, CMI/LMI: 556/556, BPS (in/new/out): 00000/00000/00000, Tips (non-/semi-lazy): 10056/0```

**Comment by muXxer** [comment]
We should investigate why the tip pool is so full.

The node was still connected to neighbors, but didn't receive messages.

**Comment by muXxer** [comment]
[goroutine.debug2.txt](https://github.com/iotaledger/hornet/files/9443355/goroutine.debug2.txt)

**Comment by muXxer** [comment]
It looks like the Send routine in INX was hanging.

It is high likely that this caused the side effects we see here, even if I don't understand the mechanism.
There were already some fixes that could avoid this to happen (like keepalive), so we will close this issue for now, but have a look if it happens again.

```
goroutine 5184 [select, 1414 minutes]:
google.golang.org/grpc/internal/transport.(*writeQuota).get(...)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/flowcontrol.go:59
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc002a9e340, 0xc0ce4a6240, {0xc0b06c8dd2, 0x5, 0x5}, {0xc0382121e0, 0xe3, 0xe3}, 0x0?)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_server.go:1096 +0x21a
google.golang.org/grpc.(*serverStream).SendMsg(0xc0004760d0, {0x1e0b8e0?, 0xc038208b40})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:1543 +0x1c2
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc074d93668, {0x1e0b8e0?, 0xc038208b40?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:156 +0x33
github.com/iotaledger/inx/go.(*iNXReadMilestoneConeMetadataServer).Send(0xaf15868a4e6a9dd7?, 0x920a56ee46bc191a?)
	/go/pkg/mod/github.com/iotaledger/inx/go@v1.0.0-beta.5/inx_grpc.pb.go:913 +0x2b
github.com/iotaledger/hornet/v2/plugins/inx.(*Server).ReadMilestoneConeMetadata.func1(0x7f6f85efd5b8?)
	/scratch/plugins/inx/server_milestones.go:369 +0x88
github.com/iotaledger/hornet/v2/plugins/inx.milestoneCone.func2(0xc061e07340?)
	/scratch/plugins/inx/server_milestones.go:402 +0x9b
github.com/iotaledger/hornet/v2/pkg/dag.(*ParentsTraverser).processStackParents(0xc0c2f036c0)
	/scratch/pkg/dag/parents_traverser.go:212 +0xd0a
github.com/iotaledger/hornet/v2/pkg/dag.(*ParentsTraverser).Traverse(0xc0c2f036c0, {0x234cdd0?, 0xc000186e40?}, {0xc001e82380, 0x4, 0x10?}, 0xc000100400?, 0xc0d0d8d2d0?, 0x0?, 0x0, ...)
	/scratch/pkg/dag/parents_traverser.go:94 +0x46d
github.com/iotaledger/hornet/v2/pkg/dag.TraverseParents({0x234cdd0, 0xc000186e40}, {0x2349320?, 0xc074d936b0}, {0xc001e82380, 0x4, 0x4}, 0xc002c03a10?, 0x5ca0df?, 0x0, ...)
	/scratch/pkg/dag/helper.go:29 +0x1ad
github.com/iotaledger/hornet/v2/plugins/inx.milestoneCone(0x22b, {0xc001e82380, 0x4, 0x4}, 0xc074d93698)
	/scratch/plugins/inx/server_milestones.go:382 +0x2b9
github.com/iotaledger/hornet/v2/plugins/inx.(*Server).ReadMilestoneConeMetadata(0xc074d93668?, 0x1d688a0?, {0x2355370?, 0xc0d0d8d260})
	/scratch/plugins/inx/server_milestones.go:363 +0x18e
github.com/iotaledger/inx/go._INX_ReadMilestoneConeMetadata_Handler({0x1e42720?, 0xc00244cf50}, {0x23530f8, 0xc074d93668})
	/go/pkg/mod/github.com/iotaledger/inx/go@v1.0.0-beta.5/inx_grpc.pb.go:900 +0xd3
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x1e42720, 0xc00244cf50}, {0x2353890?, 0xc0004760d0}, 0x1b9b4c0?, 0x2145478)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x109
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0023001e0, {0x2359920, 0xc002a9e340}, 0xc0ce4a6240, 0xc00249fd70, 0x2efb6e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1565 +0xfa6
google.golang.org/grpc.(*Server).handleStream(0xc0023001e0, {0x2359920, 0xc002a9e340}, 0xc0ce4a6240, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1640 +0x9ea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
```
